spring.application.name=app-backend-atelie

# Configurações do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/ateliecibs?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracoes do Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true

# Variaveis de ambiente para o JWT
api.security.token.secret=${JWT_SECRET:mysecretkey}

# Configuracao de CORS - origens permitidas (separadas por virgula)
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}


# Configurações do Gemini
gemini.api.key="AIzaSyAp2p3Lo5OFm2cOQ97tCXrXuLoxuaWOtvk"

# Configurações da API Shopee
shopee.api.base-url=https://openplatform.sandbox.test-stable.shopee.sg
shopee.api.partner-id=${SHOPEE_PARTNER_ID:1231968}
shopee.api.partner-key=${SHOPEE_PARTNER_KEY:shpk72736e6c537a4d69754354784847704c4b4a56556f554e6d76436651506b}
shopee.api.refresh-token-path=/api/v2/auth/access_token/get
shopee.api.refresh-margin-minutes=15

